/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as CadastroAnuncianteRouteImport } from './routes/cadastro-anunciante'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/app'
import { Route as AnuncianteRouteImport } from './routes/anunciante'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LegalTermosRouteImport } from './routes/legal/termos'
import { Route as LegalRenovacaoRouteImport } from './routes/legal/renovacao'
import { Route as LegalPrivacidadeRouteImport } from './routes/legal/privacidade'
import { Route as LegalBonificacaoRouteImport } from './routes/legal/bonificacao'
import { Route as LegalAntifraudeRouteImport } from './routes/legal/antifraude'
import { Route as AppRenovacaoRouteImport } from './routes/app/renovacao'
import { Route as AppRedeRouteImport } from './routes/app/rede'
import { Route as AppExtratoRouteImport } from './routes/app/extrato'
import { Route as AppCampanhasRouteImport } from './routes/app/campanhas'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as AdminSaquesRouteImport } from './routes/admin/saques'
import { Route as AdminProvasRouteImport } from './routes/admin/provas'
import { Route as AdminPacotesRouteImport } from './routes/admin/pacotes'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminCampanhasRouteImport } from './routes/admin/campanhas'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as AppCheckoutPackageIdRouteImport } from './routes/app/checkout.$packageId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments-webhook'
import { Route as ApiPublicEmailConfirmationSendRouteImport } from './routes/api/public/email-confirmation/send'
import { Route as ApiPublicEmailConfirmationConfirmRouteImport } from './routes/api/public/email-confirmation/confirm'
import { Route as ApiPublicCaktoWebhookRouteImport } from './routes/api/public/cakto/webhook'
import { Route as ApiPublicCaktoCreateCheckoutRouteImport } from './routes/api/public/cakto/create-checkout'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroAnuncianteRoute = CadastroAnuncianteRouteImport.update({
  id: '/cadastro-anunciante',
  path: '/cadastro-anunciante',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncianteRoute = AnuncianteRouteImport.update({
  id: '/anunciante',
  path: '/anunciante',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LegalTermosRoute = LegalTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRenovacaoRoute = LegalRenovacaoRouteImport.update({
  id: '/renovacao',
  path: '/renovacao',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacidadeRoute = LegalPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => LegalRoute,
} as any)
const LegalBonificacaoRoute = LegalBonificacaoRouteImport.update({
  id: '/bonificacao',
  path: '/bonificacao',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAntifraudeRoute = LegalAntifraudeRouteImport.update({
  id: '/antifraude',
  path: '/antifraude',
  getParentRoute: () => LegalRoute,
} as any)
const AppRenovacaoRoute = AppRenovacaoRouteImport.update({
  id: '/renovacao',
  path: '/renovacao',
  getParentRoute: () => AppRoute,
} as any)
const AppRedeRoute = AppRedeRouteImport.update({
  id: '/rede',
  path: '/rede',
  getParentRoute: () => AppRoute,
} as any)
const AppExtratoRoute = AppExtratoRouteImport.update({
  id: '/extrato',
  path: '/extrato',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSaquesRoute = AdminSaquesRouteImport.update({
  id: '/saques',
  path: '/saques',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvasRoute = AdminProvasRouteImport.update({
  id: '/provas',
  path: '/provas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacotesRoute = AdminPacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampanhasRoute = AdminCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const AppCheckoutPackageIdRoute = AppCheckoutPackageIdRouteImport.update({
  id: '/checkout/$packageId',
  path: '/checkout/$packageId',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments-webhook',
    path: '/api/public/payments-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailConfirmationSendRoute =
  ApiPublicEmailConfirmationSendRouteImport.update({
    id: '/api/public/email-confirmation/send',
    path: '/api/public/email-confirmation/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmailConfirmationConfirmRoute =
  ApiPublicEmailConfirmationConfirmRouteImport.update({
    id: '/api/public/email-confirmation/confirm',
    path: '/api/public/email-confirmation/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCaktoWebhookRoute = ApiPublicCaktoWebhookRouteImport.update({
  id: '/api/public/cakto/webhook',
  path: '/api/public/cakto/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaktoCreateCheckoutRoute =
  ApiPublicCaktoCreateCheckoutRouteImport.update({
    id: '/api/public/cakto/create-checkout',
    path: '/api/public/cakto/create-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anunciante': typeof AnuncianteRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/cadastro-anunciante': typeof CadastroAnuncianteRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/pacotes': typeof AdminPacotesRoute
  '/admin/provas': typeof AdminProvasRoute
  '/admin/saques': typeof AdminSaquesRoute
  '/api/config': typeof ApiConfigRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/rede': typeof AppRedeRoute
  '/app/renovacao': typeof AppRenovacaoRoute
  '/legal/antifraude': typeof LegalAntifraudeRoute
  '/legal/bonificacao': typeof LegalBonificacaoRoute
  '/legal/privacidade': typeof LegalPrivacidadeRoute
  '/legal/renovacao': typeof LegalRenovacaoRoute
  '/legal/termos': typeof LegalTermosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/payments-webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/checkout/$packageId': typeof AppCheckoutPackageIdRoute
  '/api/public/cakto/create-checkout': typeof ApiPublicCaktoCreateCheckoutRoute
  '/api/public/cakto/webhook': typeof ApiPublicCaktoWebhookRoute
  '/api/public/email-confirmation/confirm': typeof ApiPublicEmailConfirmationConfirmRoute
  '/api/public/email-confirmation/send': typeof ApiPublicEmailConfirmationSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anunciante': typeof AnuncianteRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-anunciante': typeof CadastroAnuncianteRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/pacotes': typeof AdminPacotesRoute
  '/admin/provas': typeof AdminProvasRoute
  '/admin/saques': typeof AdminSaquesRoute
  '/api/config': typeof ApiConfigRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/rede': typeof AppRedeRoute
  '/app/renovacao': typeof AppRenovacaoRoute
  '/legal/antifraude': typeof LegalAntifraudeRoute
  '/legal/bonificacao': typeof LegalBonificacaoRoute
  '/legal/privacidade': typeof LegalPrivacidadeRoute
  '/legal/renovacao': typeof LegalRenovacaoRoute
  '/legal/termos': typeof LegalTermosRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/public/payments-webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/checkout/$packageId': typeof AppCheckoutPackageIdRoute
  '/api/public/cakto/create-checkout': typeof ApiPublicCaktoCreateCheckoutRoute
  '/api/public/cakto/webhook': typeof ApiPublicCaktoWebhookRoute
  '/api/public/email-confirmation/confirm': typeof ApiPublicEmailConfirmationConfirmRoute
  '/api/public/email-confirmation/send': typeof ApiPublicEmailConfirmationSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/anunciante': typeof AnuncianteRoute
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/cadastro-anunciante': typeof CadastroAnuncianteRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/pacotes': typeof AdminPacotesRoute
  '/admin/provas': typeof AdminProvasRoute
  '/admin/saques': typeof AdminSaquesRoute
  '/api/config': typeof ApiConfigRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/extrato': typeof AppExtratoRoute
  '/app/rede': typeof AppRedeRoute
  '/app/renovacao': typeof AppRenovacaoRoute
  '/legal/antifraude': typeof LegalAntifraudeRoute
  '/legal/bonificacao': typeof LegalBonificacaoRoute
  '/legal/privacidade': typeof LegalPrivacidadeRoute
  '/legal/renovacao': typeof LegalRenovacaoRoute
  '/legal/termos': typeof LegalTermosRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/public/payments-webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/checkout/$packageId': typeof AppCheckoutPackageIdRoute
  '/api/public/cakto/create-checkout': typeof ApiPublicCaktoCreateCheckoutRoute
  '/api/public/cakto/webhook': typeof ApiPublicCaktoWebhookRoute
  '/api/public/email-confirmation/confirm': typeof ApiPublicEmailConfirmationConfirmRoute
  '/api/public/email-confirmation/send': typeof ApiPublicEmailConfirmationSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anunciante'
    | '/app'
    | '/cadastro'
    | '/cadastro-anunciante'
    | '/legal'
    | '/login'
    | '/admin/admins'
    | '/admin/campanhas'
    | '/admin/logs'
    | '/admin/pacotes'
    | '/admin/provas'
    | '/admin/saques'
    | '/api/config'
    | '/app/campanhas'
    | '/app/extrato'
    | '/app/rede'
    | '/app/renovacao'
    | '/legal/antifraude'
    | '/legal/bonificacao'
    | '/legal/privacidade'
    | '/legal/renovacao'
    | '/legal/termos'
    | '/admin/'
    | '/app/'
    | '/api/public/payments-webhook'
    | '/app/checkout/$packageId'
    | '/api/public/cakto/create-checkout'
    | '/api/public/cakto/webhook'
    | '/api/public/email-confirmation/confirm'
    | '/api/public/email-confirmation/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anunciante'
    | '/cadastro'
    | '/cadastro-anunciante'
    | '/legal'
    | '/login'
    | '/admin/admins'
    | '/admin/campanhas'
    | '/admin/logs'
    | '/admin/pacotes'
    | '/admin/provas'
    | '/admin/saques'
    | '/api/config'
    | '/app/campanhas'
    | '/app/extrato'
    | '/app/rede'
    | '/app/renovacao'
    | '/legal/antifraude'
    | '/legal/bonificacao'
    | '/legal/privacidade'
    | '/legal/renovacao'
    | '/legal/termos'
    | '/admin'
    | '/app'
    | '/api/public/payments-webhook'
    | '/app/checkout/$packageId'
    | '/api/public/cakto/create-checkout'
    | '/api/public/cakto/webhook'
    | '/api/public/email-confirmation/confirm'
    | '/api/public/email-confirmation/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anunciante'
    | '/app'
    | '/cadastro'
    | '/cadastro-anunciante'
    | '/legal'
    | '/login'
    | '/admin/admins'
    | '/admin/campanhas'
    | '/admin/logs'
    | '/admin/pacotes'
    | '/admin/provas'
    | '/admin/saques'
    | '/api/config'
    | '/app/campanhas'
    | '/app/extrato'
    | '/app/rede'
    | '/app/renovacao'
    | '/legal/antifraude'
    | '/legal/bonificacao'
    | '/legal/privacidade'
    | '/legal/renovacao'
    | '/legal/termos'
    | '/admin/'
    | '/app/'
    | '/api/public/payments-webhook'
    | '/app/checkout/$packageId'
    | '/api/public/cakto/create-checkout'
    | '/api/public/cakto/webhook'
    | '/api/public/email-confirmation/confirm'
    | '/api/public/email-confirmation/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnuncianteRoute: typeof AnuncianteRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CadastroAnuncianteRoute: typeof CadastroAnuncianteRoute
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicCaktoCreateCheckoutRoute: typeof ApiPublicCaktoCreateCheckoutRoute
  ApiPublicCaktoWebhookRoute: typeof ApiPublicCaktoWebhookRoute
  ApiPublicEmailConfirmationConfirmRoute: typeof ApiPublicEmailConfirmationConfirmRoute
  ApiPublicEmailConfirmationSendRoute: typeof ApiPublicEmailConfirmationSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-anunciante': {
      id: '/cadastro-anunciante'
      path: '/cadastro-anunciante'
      fullPath: '/cadastro-anunciante'
      preLoaderRoute: typeof CadastroAnuncianteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunciante': {
      id: '/anunciante'
      path: '/anunciante'
      fullPath: '/anunciante'
      preLoaderRoute: typeof AnuncianteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/legal/termos': {
      id: '/legal/termos'
      path: '/termos'
      fullPath: '/legal/termos'
      preLoaderRoute: typeof LegalTermosRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/renovacao': {
      id: '/legal/renovacao'
      path: '/renovacao'
      fullPath: '/legal/renovacao'
      preLoaderRoute: typeof LegalRenovacaoRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacidade': {
      id: '/legal/privacidade'
      path: '/privacidade'
      fullPath: '/legal/privacidade'
      preLoaderRoute: typeof LegalPrivacidadeRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/bonificacao': {
      id: '/legal/bonificacao'
      path: '/bonificacao'
      fullPath: '/legal/bonificacao'
      preLoaderRoute: typeof LegalBonificacaoRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/antifraude': {
      id: '/legal/antifraude'
      path: '/antifraude'
      fullPath: '/legal/antifraude'
      preLoaderRoute: typeof LegalAntifraudeRouteImport
      parentRoute: typeof LegalRoute
    }
    '/app/renovacao': {
      id: '/app/renovacao'
      path: '/renovacao'
      fullPath: '/app/renovacao'
      preLoaderRoute: typeof AppRenovacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rede': {
      id: '/app/rede'
      path: '/rede'
      fullPath: '/app/rede'
      preLoaderRoute: typeof AppRedeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/extrato': {
      id: '/app/extrato'
      path: '/extrato'
      fullPath: '/app/extrato'
      preLoaderRoute: typeof AppExtratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campanhas': {
      id: '/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/saques': {
      id: '/admin/saques'
      path: '/saques'
      fullPath: '/admin/saques'
      preLoaderRoute: typeof AdminSaquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/provas': {
      id: '/admin/provas'
      path: '/provas'
      fullPath: '/admin/provas'
      preLoaderRoute: typeof AdminProvasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pacotes': {
      id: '/admin/pacotes'
      path: '/pacotes'
      fullPath: '/admin/pacotes'
      preLoaderRoute: typeof AdminPacotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campanhas': {
      id: '/admin/campanhas'
      path: '/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AdminCampanhasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/checkout/$packageId': {
      id: '/app/checkout/$packageId'
      path: '/checkout/$packageId'
      fullPath: '/app/checkout/$packageId'
      preLoaderRoute: typeof AppCheckoutPackageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/payments-webhook': {
      id: '/api/public/payments-webhook'
      path: '/api/public/payments-webhook'
      fullPath: '/api/public/payments-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-confirmation/send': {
      id: '/api/public/email-confirmation/send'
      path: '/api/public/email-confirmation/send'
      fullPath: '/api/public/email-confirmation/send'
      preLoaderRoute: typeof ApiPublicEmailConfirmationSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-confirmation/confirm': {
      id: '/api/public/email-confirmation/confirm'
      path: '/api/public/email-confirmation/confirm'
      fullPath: '/api/public/email-confirmation/confirm'
      preLoaderRoute: typeof ApiPublicEmailConfirmationConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cakto/webhook': {
      id: '/api/public/cakto/webhook'
      path: '/api/public/cakto/webhook'
      fullPath: '/api/public/cakto/webhook'
      preLoaderRoute: typeof ApiPublicCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cakto/create-checkout': {
      id: '/api/public/cakto/create-checkout'
      path: '/api/public/cakto/create-checkout'
      fullPath: '/api/public/cakto/create-checkout'
      preLoaderRoute: typeof ApiPublicCaktoCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminCampanhasRoute: typeof AdminCampanhasRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPacotesRoute: typeof AdminPacotesRoute
  AdminProvasRoute: typeof AdminProvasRoute
  AdminSaquesRoute: typeof AdminSaquesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminCampanhasRoute: AdminCampanhasRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPacotesRoute: AdminPacotesRoute,
  AdminProvasRoute: AdminProvasRoute,
  AdminSaquesRoute: AdminSaquesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppExtratoRoute: typeof AppExtratoRoute
  AppRedeRoute: typeof AppRedeRoute
  AppRenovacaoRoute: typeof AppRenovacaoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCheckoutPackageIdRoute: typeof AppCheckoutPackageIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampanhasRoute: AppCampanhasRoute,
  AppExtratoRoute: AppExtratoRoute,
  AppRedeRoute: AppRedeRoute,
  AppRenovacaoRoute: AppRenovacaoRoute,
  AppIndexRoute: AppIndexRoute,
  AppCheckoutPackageIdRoute: AppCheckoutPackageIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LegalRouteChildren {
  LegalAntifraudeRoute: typeof LegalAntifraudeRoute
  LegalBonificacaoRoute: typeof LegalBonificacaoRoute
  LegalPrivacidadeRoute: typeof LegalPrivacidadeRoute
  LegalRenovacaoRoute: typeof LegalRenovacaoRoute
  LegalTermosRoute: typeof LegalTermosRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalAntifraudeRoute: LegalAntifraudeRoute,
  LegalBonificacaoRoute: LegalBonificacaoRoute,
  LegalPrivacidadeRoute: LegalPrivacidadeRoute,
  LegalRenovacaoRoute: LegalRenovacaoRoute,
  LegalTermosRoute: LegalTermosRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnuncianteRoute: AnuncianteRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CadastroAnuncianteRoute: CadastroAnuncianteRoute,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicCaktoCreateCheckoutRoute: ApiPublicCaktoCreateCheckoutRoute,
  ApiPublicCaktoWebhookRoute: ApiPublicCaktoWebhookRoute,
  ApiPublicEmailConfirmationConfirmRoute:
    ApiPublicEmailConfirmationConfirmRoute,
  ApiPublicEmailConfirmationSendRoute: ApiPublicEmailConfirmationSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
