-- bonuses.origem_id points at the user_cycles row whose adesão/renovação
-- generated the bonus (NOT a users_profile id) and has no foreign key
-- constraint at all, so deleting or blocking the referred user never
-- touched the upline's still-pending bonus/hold rows — they kept being
-- auto-released by release_available_balances() (cron job
-- release-balance-holds-hourly) even after the referral that generated
-- them was removed.
--
-- This function cancels any still-pending bonus (and its balance_holds
-- row) whose origin cycle belongs to a given referred user, reversing the
-- saldo_a_liberar that was reserved for it. Bonuses already released are
-- left untouched (the money is already credited) — admins can spot those
-- via the new "origem removida" flag added to /admin/rede.
create or replace function public.cancel_pending_bonuses_for_referred_user(p_referred_profile_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bonus record;
  v_count integer := 0;
begin
  for v_bonus in
    select b.id, b.user_id, b.valor
    from public.bonuses b
    join public.user_cycles uc on uc.id = b.origem_id
    where uc.user_id = p_referred_profile_id
      and b.status = 'pendente'
  loop
    update public.balance_holds
    set status = 'cancelado'
    where bonus_id = v_bonus.id and status = 'bloqueado';

    update public.wallet_balances
    set saldo_a_liberar = greatest(0, saldo_a_liberar - v_bonus.valor),
        updated_at = now()
    where user_id = v_bonus.user_id;

    update public.bonuses
    set status = 'cancelado'
    where id = v_bonus.id;

    perform public.audit_business_event(
      v_bonus.user_id, 'bonus_cancelado_referido_removido', v_bonus.valor, null,
      'bonuses', v_bonus.id, 'cancelado'
    );
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

grant execute on function public.cancel_pending_bonuses_for_referred_user(uuid) to service_role, authenticated;

-- Hook the cancellation into the existing pre-delete cleanup so excluding a
-- user from the admin panel also cancels bonuses generated by their cycles
-- before user_cycles cascade-deletes (which would otherwise orphan origem_id).
create or replace function public.admin_predelete_user_cleanup(p_auth_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
  v_advertiser_id uuid;
  rec record;
  v_schema text;
  v_table text;
  v_nullable boolean;
  v_sql text;
begin
  select id into v_profile_id from public.users_profile where auth_user_id = p_auth_user_id;
  select id into v_advertiser_id from public.advertiser_profiles where auth_user_id = p_auth_user_id;

  if v_profile_id is not null then
    perform public.cancel_pending_bonuses_for_referred_user(v_profile_id);
  end if;

  for rec in
    select
      c.conrelid::regclass::text as tbl,
      a.attname as col,
      c.confrelid::regclass::text as reftbl
    from pg_constraint c
    join pg_attribute a on a.attrelid = c.conrelid and a.attnum = c.conkey[1]
    where c.contype = 'f'
      and c.confrelid in ('auth.users'::regclass, 'public.users_profile'::regclass, 'public.advertiser_profiles'::regclass)
      and c.confdeltype <> 'c'
      and array_length(c.conkey, 1) = 1
  loop
    if position('.' in rec.tbl) > 0 then
      v_schema := split_part(rec.tbl, '.', 1);
      v_table := split_part(rec.tbl, '.', 2);
    else
      v_schema := 'public';
      v_table := rec.tbl;
    end if;

    select (is_nullable = 'YES') into v_nullable
      from information_schema.columns
      where table_schema = v_schema and table_name = v_table and column_name = rec.col;

    if v_nullable then
      v_sql := format('update %I.%I set %I = null where %I = $1', v_schema, v_table, rec.col, rec.col);
    else
      v_sql := format('delete from %I.%I where %I = $1', v_schema, v_table, rec.col);
    end if;

    if rec.reftbl = 'auth.users' then
      execute v_sql using p_auth_user_id;
    elsif rec.reftbl = 'public.users_profile' and v_profile_id is not null then
      execute v_sql using v_profile_id;
    elsif rec.reftbl = 'public.advertiser_profiles' and v_advertiser_id is not null then
      execute v_sql using v_advertiser_id;
    end if;
  end loop;
end;
$$;

grant execute on function public.admin_predelete_user_cleanup(uuid) to service_role;
